services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head  # Run Alembic migrations during the build phase
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
