"""description of changes

Revision ID: 22d241b01b1b
Revises: e05a62e8a63b
Create Date: 2024-08-01 15:56:59.596370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d241b01b1b'
down_revision: Union[str, None] = 'e05a62e8a63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('overall_score', sa.Float(), nullable=False, server_default=sa.text("'0'::double precision")))
    op.drop_column('recipes', 'overall_Score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('overall_Score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'overall_score')
    # ### end Alembic commands ###
