"""Add ingredient column to recipe table

Revision ID: 2e914885e20f
Revises: 1033dfebbb75
Create Date: 2024-07-28 06:07:13.632204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e914885e20f'
down_revision: Union[str, None] = '1033dfebbb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###
