"""Add image column to recipe

Revision ID: 419499bb230e
Revises: 2e914885e20f
Create Date: 2024-07-29 09:49:53.762576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419499bb230e'
down_revision: Union[str, None] = '2e914885e20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image', sa.String(), nullable=False,  server_default='https://example.com/default_image.jpg'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image')
    # ### end Alembic commands ###
