"""your_migration_message

Revision ID: 8ceab347d3f6
Revises: 4e3fde96cc3f
Create Date: 2024-08-20 03:35:31.826211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ceab347d3f6'
down_revision: Union[str, None] = '4e3fde96cc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
