"""Make Recipe liked_by a list

Revision ID: a6e043a638da
Revises: c3183eb5ae76
Create Date: 2024-08-02 17:28:35.703191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e043a638da'
down_revision: Union[str, None] = 'c3183eb5ae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
