"""Set up Scan History

Revision ID: a892bb8282b4
Revises: 7461ffa630e4
Create Date: 2024-08-17 17:32:11.482022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a892bb8282b4'
down_revision: Union[str, None] = '7461ffa630e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_histories', sa.Column('scan_result', sa.JSON(), nullable=False))
    op.drop_constraint('scan_histories_meal_id_fkey', 'scan_histories', type_='foreignkey')
    op.drop_column('scan_histories', 'meal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_histories', sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scan_histories_meal_id_fkey', 'scan_histories', 'meals', ['meal_id'], ['id'])
    op.drop_column('scan_histories', 'scan_result')
    # ### end Alembic commands ###
