"""Add default vlaue of streak last activity

Revision ID: b7ae8dfa93c3
Revises: 67cfccf64b1c
Create Date: 2024-07-23 22:35:07.439534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ae8dfa93c3'
down_revision: Union[str, None] = '67cfccf64b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
