"""Update recipe format to be the same as scan result format

Revision ID: cb1739e908b6
Revises: a892bb8282b4
Create Date: 2024-08-17 18:10:06.704420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1739e908b6'
down_revision: Union[str, None] = 'a892bb8282b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('fiber_content', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('recipes', sa.Column('net_carb', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('recipes', sa.Column('fat', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('recipes', sa.Column('portion_size_recommendations', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    op.add_column('recipes', sa.Column('cholesterol', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'cholesterol')
    op.drop_column('recipes', 'portion_size_recommendations')
    op.drop_column('recipes', 'fat')
    op.drop_column('recipes', 'net_carb')
    op.drop_column('recipes', 'fiber_content')
    # ### end Alembic commands ###
