"""Add migrations for profile image and more

Revision ID: dd9ab719d44d
Revises: 5ffc85cb5d28
Create Date: 2024-08-19 14:15:36.141203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9ab719d44d'
down_revision: Union[str, None] = '5ffc85cb5d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
