"""Update recipe format to be the same as scan result format

Revision ID: f4da891f3fd6
Revises: cb1739e908b6
Create Date: 2024-08-17 23:04:35.976467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4da891f3fd6'
down_revision: Union[str, None] = 'cb1739e908b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
